/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.devcon.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Talk service. Represents a row in the &quot;_Talk&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.devcon.model.impl.TalkModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.devcon.model.impl.TalkImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Talk
 * @generated
 */
@ProviderType
public interface TalkModel
	extends BaseModel<Talk>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a talk model instance should use the {@link Talk} interface instead.
	 */

	/**
	 * Returns the primary key of this talk.
	 *
	 * @return the primary key of this talk
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this talk.
	 *
	 * @param primaryKey the primary key of this talk
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this talk.
	 *
	 * @return the uuid of this talk
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this talk.
	 *
	 * @param uuid the uuid of this talk
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the talk ID of this talk.
	 *
	 * @return the talk ID of this talk
	 */
	public long getTalkId();

	/**
	 * Sets the talk ID of this talk.
	 *
	 * @param talkId the talk ID of this talk
	 */
	public void setTalkId(long talkId);

	/**
	 * Returns the group ID of this talk.
	 *
	 * @return the group ID of this talk
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this talk.
	 *
	 * @param groupId the group ID of this talk
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this talk.
	 *
	 * @return the company ID of this talk
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this talk.
	 *
	 * @param companyId the company ID of this talk
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this talk.
	 *
	 * @return the user ID of this talk
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this talk.
	 *
	 * @param userId the user ID of this talk
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this talk.
	 *
	 * @return the user uuid of this talk
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this talk.
	 *
	 * @param userUuid the user uuid of this talk
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this talk.
	 *
	 * @return the user name of this talk
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this talk.
	 *
	 * @param userName the user name of this talk
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this talk.
	 *
	 * @return the create date of this talk
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this talk.
	 *
	 * @param createDate the create date of this talk
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this talk.
	 *
	 * @return the modified date of this talk
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this talk.
	 *
	 * @param modifiedDate the modified date of this talk
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this talk.
	 *
	 * @return the name of this talk
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this talk.
	 *
	 * @param name the name of this talk
	 */
	public void setName(String name);

	/**
	 * Returns the speaker of this talk.
	 *
	 * @return the speaker of this talk
	 */
	@AutoEscape
	public String getSpeaker();

	/**
	 * Sets the speaker of this talk.
	 *
	 * @param speaker the speaker of this talk
	 */
	public void setSpeaker(String speaker);

	/**
	 * Returns the description of this talk.
	 *
	 * @return the description of this talk
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this talk.
	 *
	 * @param description the description of this talk
	 */
	public void setDescription(String description);

	/**
	 * Returns the start date of this talk.
	 *
	 * @return the start date of this talk
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this talk.
	 *
	 * @param startDate the start date of this talk
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this talk.
	 *
	 * @return the end date of this talk
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this talk.
	 *
	 * @param endDate the end date of this talk
	 */
	public void setEndDate(Date endDate);

}